#!/bin/sh
	update-alternatives --remove  passwd /home/quectel/alessa_linux164/Qualcomm/MDM9x28/OpenLinux/LE2.0.1/main/MCU_R05/apps_proc/poky/build/tmp-glibc/deploy/sdk/ql-ol-sdk/ql-ol-crosstool/sysroots/x86_64-oesdk-linux/usr/bin/passwd.shadow
	update-alternatives --remove  chfn /home/quectel/alessa_linux164/Qualcomm/MDM9x28/OpenLinux/LE2.0.1/main/MCU_R05/apps_proc/poky/build/tmp-glibc/deploy/sdk/ql-ol-sdk/ql-ol-crosstool/sysroots/x86_64-oesdk-linux/usr/bin/chfn.shadow
	update-alternatives --remove  chsh /home/quectel/alessa_linux164/Qualcomm/MDM9x28/OpenLinux/LE2.0.1/main/MCU_R05/apps_proc/poky/build/tmp-glibc/deploy/sdk/ql-ol-sdk/ql-ol-crosstool/sysroots/x86_64-oesdk-linux/usr/bin/chsh.shadow
	update-alternatives --remove  chpasswd /home/quectel/alessa_linux164/Qualcomm/MDM9x28/OpenLinux/LE2.0.1/main/MCU_R05/apps_proc/poky/build/tmp-glibc/deploy/sdk/ql-ol-sdk/ql-ol-crosstool/sysroots/x86_64-oesdk-linux/usr/bin/chpasswd.shadow
	update-alternatives --remove  vipw /home/quectel/alessa_linux164/Qualcomm/MDM9x28/OpenLinux/LE2.0.1/main/MCU_R05/apps_proc/poky/build/tmp-glibc/deploy/sdk/ql-ol-sdk/ql-ol-crosstool/sysroots/x86_64-oesdk-linux/sbin/vipw.shadow
	update-alternatives --remove  vigr /home/quectel/alessa_linux164/Qualcomm/MDM9x28/OpenLinux/LE2.0.1/main/MCU_R05/apps_proc/poky/build/tmp-glibc/deploy/sdk/ql-ol-sdk/ql-ol-crosstool/sysroots/x86_64-oesdk-linux/sbin/vigr.shadow
