	# remove syslog
	if test "x$D" = "x"; then
		if test "$1" = "upgrade" -o "$1" = "remove"; then
			/etc/init.d/syslog stop
		fi
	fi
	update-alternatives --remove  syslog-conf /etc/syslog.conf.busybox
	update-alternatives --remove  syslog-init /etc/init.d/syslog.busybox
	update-alternatives --remove  syslog-startup-conf /etc/syslog-startup.conf.busybox
if [ -z "$D" ]; then
	/etc/init.d/syslog stop
fi
